channels:
  - conda-forge
  - usgs-astrogeology
  - menpo
dependencies:
  - python >= 3
  - coveralls
  - csmapi
  - cyvlfeat
  - geoalchemy2
  - geopandas
  - imageio
  - ipykernel
  - jupyter
  - knoten
  - ncurses
  - networkx
  - numpy
  - opencv <= 3.5
  - pillow
  - pip
  - pip:
    - redis
  - plio >= 1.1.0
  - plurmy
  - psycopg2
  - pyproj
  - pytest
  - pytest-cov
  - pysis
  - scikit-image
  - scipy
  - shapely
  - sqlalchemy
  - sqlalchemy-utils
  - usgs-astrogeology/label/dev::usgscsm
  - vlfeat
