name: autocnet
channels:
  - conda-forge
  - usgs-astrogeology
  - menpo
dependencies:
  - python=3
  - numpy
  - scipy
  - scikit-image
  - opencv
  - vlfeat
  - cyvlfeat
  - csmapi
  - networkx
  - pillow
  - plio
  - ncurses
  - geopandas
  - pytest
  - pytest-cov
  - coveralls
  - anaconda-client
