name: autocnet2
channels:
  - conda-forge
  - jlaura
  - menpo
dependencies:
  - python=3
  - libpng
  - opencv
  - gdal
  - h5py
  - cython
  - matplotlib
  - dill
  - jupyter
  - networkx
  - numexpr
  - numpy>1.10.0
  - pandas
  - geopandas
  - shapely
  - pyyaml
  - scipy>0.17.0
  - sqlalchemy
  - pip:
    - pillow
    - pvl
    - libpysal
    - protobuf
