### Cluster Configuration ###
cluster:
    # The number of times to retry a failing cluster job
    maxfailures: 3
    # Which processing queue should be used?
    queue: 'shortall'
    # Location to put <jobid.log> files for cluster jobs
    cluster_log_dir: '/scratch/jlaura/elysium/logs'
    cluster_submission: 'slurm'  # or `pbs`
    tmp_scratch_dir: '/scratch/jlaura'

    # The amount of RAM (in MB) to request for jobs
    extractor_memory: 8192
    processing_memory: 8192

### Database Configuration ###
database:
    type: 'postgresql'
    username: 'postgres'
    password: ''
    host: 'localhost'
    port: 5432 # This is a mapped port when postgresql is containerized, e.g., 8085
    pgbouncer_port: 5432  # This is normally a different port, e.g., 8083
    # The name of the database to connect to.  Tables will be created inside this DB.
    name: 'travis_ci_test' # This needs to be all lowercase for PostGreSQL!
    # The number of seconds to wait while attemping to connect to the DB.
    timeout: 500

### Pfeffernusse / CSM Configuration ###
pfeffernusse:
    url: 'http://smalls:8081/v1/pds'

# Redis Configuration
redis:
    basename: 'elysium'
    host: 'smalls'
    port: '8084'
    completed_queue: 'jely:done'
    processing_queue: 'jely:proc'
    working_queue: 'jely:working'

### Spatial Reference Setup ###
spatial:
    latitudinal_srid: 4326  # For testing we use WGS84.
    rectangular_srid: 4978
    semimajor_rad: 3396190  # in meters
    semiminor_rad: 3376200  # in meters
    proj4_str: '+proj:longlat +a:3396190 +b:3376200 +no_defs'
    dem: None

### Working Directories ###
directories:
    vrt_dir: '/sratch/jlaura/elysium/vrt'

algorithms:
    ring_match:
        - target_points: 25
          tolerance: 0.01
        - target_points: 20
          tolerance: 0.01
        - target_points: 25
          tolerance: 0.02
    compute_fundamental_matrix:
        - tolerance: 0.3
          reproj_threshold: 10
          initial_x_size: 500
          initial_y_size: 500
          corr_x_size: 40
          corr_y_size: 40
        - tolerance: 0.3
          reproj_threshold: 15
          initial_x_size: 500
          initial_y_size: 500
          corr_x_size: 40
          corr_y_size: 40
        - tolerance: 0.25
          reproj_threshold: 20
          initial_x_size: 500
          initial_y_size: 500
          corr_x_size: 40
          corr_y_size: 40
